# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SubZeroDev.HotCorners.Preview
PackageVersion: 1.0.0-preview.1
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{DC957C56-DEC9-4C45-8D26-5C9254579486}'
ReleaseDate: 2026-10-04
AppsAndFeaturesEntries:
- DisplayName: SubZeroDev.HotCorners
  Publisher: SubZeroDev
  DisplayVersion: 1.0.0-preview.1
  ProductCode: '{DC957C56-DEC9-4C45-8D26-5C9254579486}'
  UpgradeCode: '{982E31BF-8BAE-5FD4-A4BB-8A7BB6502101}'
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%/SubZeroDev.HotCorners'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/The-Running-Dev/SubZeroDev.HotCorners.Releases/releases/download/v1.0.0-preview.1/SubZeroDev.HotCorners-1.0.0-preview.1-win-preview.msi
  InstallerSha256: D40D6696B0B2C2909150132ACB32C2B9721692B3EC8E003A0266D6DCF0C081DB
ManifestType: installer
ManifestVersion: 1.12.0
