# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: CologneCodeCompany.XYplorer
PackageVersion: 26.20.0200
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
Commands:
- xyplorer
Installers:
- Architecture: x64
  InstallerUrl: https://www.xyplorer.com/download/XYplorer_26.20_Install.exe
  InstallerSha256: 7E85BB39BDEAD97AC442CEFDC5553124046DC659C64D8E11CDFAE66586C9AC52
ManifestType: installer
ManifestVersion: 1.6.0
